export default defineEventHandler((_event: unknown) => {
  return {
    data: {
      pages: {
        tree: [
          {
            id: 807,
            path: 'web/play/api',
            depth: 3,
            title: 'API 방식',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 806,
            pageId: 111,
            locale: 'ko',
          },
          {
            id: 800,
            path: 'web/etc',
            depth: 2,
            title: 'etc',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: null,
            locale: 'ko',
          },
          {
            id: 786,
            path: 'web/auth/gnb',
            depth: 3,
            title: 'GNB 방식',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 785,
            pageId: 28,
            locale: 'ko',
          },
          {
            id: 863,
            path: 'web',
            depth: 1,
            title: 'web',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 0,
            pageId: null,
            locale: 'vi',
          },
          {
            id: 61,
            path: 'web',
            depth: 1,
            title: 'web',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 0,
            pageId: null,
            locale: 'en',
          },
          {
            id: 782,
            path: 'web',
            depth: 1,
            title: 'WEB',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 0,
            pageId: 67,
            locale: 'ko',
          },
          {
            id: 806,
            path: 'web/play',
            depth: 2,
            title: '게임 실행',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: 32,
            locale: 'ko',
          },
          {
            id: 790,
            path: 'web/billing',
            depth: 2,
            title: '빌링',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: 120,
            locale: 'ko',
          },
          {
            id: 815,
            path: 'web/weblog',
            depth: 2,
            title: '웹 로그',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: 54,
            locale: 'ko',
          },
          {
            id: 785,
            path: 'web/auth',
            depth: 2,
            title: '인증',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: 27,
            locale: 'ko',
          },
          {
            id: 792,
            path: 'web/character',
            depth: 2,
            title: '캐릭터',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: 43,
            locale: 'ko',
          },
          {
            id: 795,
            path: 'web/coupon',
            depth: 2,
            title: '쿠폰',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: 48,
            locale: 'ko',
          },
          {
            id: 803,
            path: 'web/member',
            depth: 2,
            title: '회원',
            isPrivate: false,
            isFolder: true,
            privateNS: null,
            parent: 782,
            pageId: 41,
            locale: 'ko',
          },
          {
            id: 801,
            path: 'web/etc/Generator',
            depth: 3,
            title: 'Command Args. Generator',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 800,
            pageId: 231,
            locale: 'ko',
          },
          {
            id: 787,
            path: 'web/auth/gnb/web_auth_gnb_design',
            depth: 4,
            title: 'GNB 디자인',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 786,
            pageId: 29,
            locale: 'ko',
          },
          {
            id: 788,
            path: 'web/auth/gnb/web_auth_gnb_option',
            depth: 4,
            title: 'GNB 옵션',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 786,
            pageId: 30,
            locale: 'ko',
          },
          {
            id: 805,
            path: 'web/page_2',
            depth: 2,
            title: 'Page2',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 782,
            pageId: 264,
            locale: 'ko',
          },
          {
            id: 813,
            path: 'web/play/web_play_seed_public',
            depth: 3,
            title: 'SEED Public 방식',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 806,
            pageId: 33,
            locale: 'ko',
          },
          {
            id: 804,
            path: 'web/member/api_member_game_id',
            depth: 3,
            title: '게임유저 아이디 조회 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 803,
            pageId: 42,
            locale: 'ko',
          },
          {
            id: 814,
            path: 'web/play/web_play_terms',
            depth: 3,
            title: '게임이용약관동의 페이지',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 806,
            pageId: 84,
            locale: 'ko',
          },
          {
            id: 811,
            path: 'web/play/api/api_maintenance_whiteuser_check',
            depth: 4,
            title: '게임점검 화이트리스트 체크 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 807,
            pageId: 38,
            locale: 'ko',
          },
          {
            id: 810,
            path: 'web/play/api/api_maintenance_total',
            depth: 4,
            title: '게임점검체크 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 807,
            pageId: 37,
            locale: 'ko',
          },
          {
            id: 791,
            path: 'web/billing/api_read_gamecash',
            depth: 3,
            title: '게임캐시 잔액조회 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 790,
            pageId: 47,
            locale: 'ko',
          },
          {
            id: 808,
            path: 'web/play/api/api_gs_clientinfo',
            depth: 4,
            title: '런처 다운로드 주소 조회 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 807,
            pageId: 40,
            locale: 'ko',
          },
          {
            id: 809,
            path: 'web/play/api/api_gs_launcherinfo',
            depth: 4,
            title: '런처 실행코드 조회 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 807,
            pageId: 39,
            locale: 'ko',
          },
          {
            id: 816,
            path: 'web/weblog/log_script',
            depth: 3,
            title: '로그 전송 Script',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 815,
            pageId: 55,
            locale: 'ko',
          },
          {
            id: 789,
            path: 'web/auth/web_auth_url',
            depth: 3,
            title: '로그인 URL 방식',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 785,
            pageId: 31,
            locale: 'ko',
          },
          {
            id: 793,
            path: 'web/character/api_character_main_change',
            depth: 3,
            title: '메인 캐릭터 변경 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 792,
            pageId: 45,
            locale: 'ko',
          },
          {
            id: 812,
            path: 'web/play/api/api_terms_agreecheck',
            depth: 4,
            title: '약관동의조회 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 807,
            pageId: 36,
            locale: 'ko',
          },
          {
            id: 802,
            path: 'web/flow_web',
            depth: 2,
            title: '연동 소개',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 782,
            pageId: 100,
            locale: 'ko',
          },
          {
            id: 794,
            path: 'web/character/api_character_read_web',
            depth: 3,
            title: '캐릭터 조회 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 792,
            pageId: 44,
            locale: 'ko',
          },
          {
            id: 799,
            path: 'web/coupon/use_gamecoupon',
            depth: 3,
            title: '쿠폰 등록 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 795,
            pageId: 50,
            locale: 'ko',
          },
          {
            id: 796,
            path: 'web/coupon/read_couponbox_list',
            depth: 3,
            title: '쿠폰함 리스트 검색 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 795,
            pageId: 52,
            locale: 'ko',
          },
          {
            id: 798,
            path: 'web/coupon/use_couponbox_coupon',
            depth: 3,
            title: '쿠폰함 쿠폰 사용 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 795,
            pageId: 53,
            locale: 'ko',
          },
          {
            id: 797,
            path: 'web/coupon/read_couponbox_list_micro',
            depth: 3,
            title: '쿠폰함 쿠폰상세 조회 API',
            isPrivate: false,
            isFolder: false,
            privateNS: null,
            parent: 795,
            pageId: 66,
            locale: 'ko',
          },
        ],
      },
    },
  };
});
